### PR TITLE
Fix injecting versioned secrets from vault-env-from-path annotation, add more tests

### LINKED ISSUE #7: Fix version issue for secret injection
The value `len(parts)` is always less than 2 due to `SplitN`.
https://github.com/bank-vaults/vault-env/blob/main/internal/injector/injector.go#L344-L351

We should also check other affected components/projects due to code duplication.

### PR DESCRIPTION
**Pull request by akijakya**
## Overview

Fixes #7 

Fix for versioned secret paths provided in `vault.security.banzaicloud.io/vault-env-from-path` annotation, also added test cases to cover versioned Vault secrets.

### CODE REVIEW

File: injector/injector.go [hunk 1]
```diff
@@ -350,8 +350,8 @@ func (i *SecretInjector) InjectSecretsFromVaultPath(paths string, inject SecretI
 
 		version := "-1"
 
-		if len(split) > 2 {
-			version = split[2]
+		if len(split) == 2 {
+			version = split[1]
```
Comment (sagikazarmark) [inline injector/injector.go:354]: I'm a little bit confused here. Given the string `secret/data/account#password#1` the two chunks will be `secret/data/account` and `password#1`.

Am I missing something?

Comment (akijakya) [reply injector/injector.go:354]: That is a good question, but according to the [docs](https://bank-vaults.dev/docs/mutating-webhook/annotations/), we expect a "_Comma-delimited list of vault paths to pull in **all secrets** as environment variables_" in the `vault.security.banzaicloud.io/vault-env-from-path` annotation, and this list is what the method in question is about. So I concluded that the intention here was to use it like this: `secret/data/account#1`. This is not stated explicitly in the docs, so if we are okay with this behaviour, I thought of submitting a PR to the docs repo as well to clarify this.

Comment (akijakya) [reply injector/injector.go:354]: This makes sense by the way because if a pod needs all of the secrets from a secret path, this annotation provides an easier alternative to adding them as envs one by one...

Comment (sagikazarmark) [reply injector/injector.go:354]: Fair enough, but then I'm not sure if this PR fixes the original issue (or maybe I misunderstood what that issue was about)

Comment (ramizpolic) [reply injector/injector.go:354]: The confusion hides in `InjectSecretsFromVault` and `InjectSecretsFromVaultPath` since they do not work in the same way. AFAIK the latter is "pseudo-subset" of the first one. We should definitely document this behaviour. Making them work the same way will break the API, so this should resolve the issue without affecting the API.

**Review by ramizpolic — APPROVED** [review]

File: injector/injector.go (hunk 1 above)
Comment (ramizpolic) [reply injector/injector.go:354]: For me, this looks good since it does resolve issue with handling the versioning in `InjectSecretsFromVaultPath`. @akijakya verified this by running the tests without the fix.

Comment (akijakya) [reply injector/injector.go:354]: Yes, `InjectSecretsFromVault` injects the singular values from one or more `secrets/path#name`, `InjectSecretsFromVaultPath` injects all secrets from one or more `secrets/path`. Maybe the names could be better, or we could include this clarification as comment...

Comment (ramizpolic) [reply injector/injector.go:354]: A comment with an example of operation for both methods would be good. But we definitely need this transparent across the docs as well.

**Review by sagikazarmark — APPROVED** [review]
